# --- CORE MOUSE ---
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_USB=y

# --- EXTERNAL MODULES ---
# These are defined by the halfdane and anti-idle modules
CONFIG_ZMK_INPUT_PROCESSORS=y
CONFIG_ZMK_ANTI_IDLE=y

# --- PERFORMANCE ---
CONFIG_USB_HID_POLL_INTERVAL_MS=1
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- POWER ---
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
