manifest:
  remotes:
    - name: moergo
      url_base: https://github.com/moergo-sc
    - name: halfdane
      url_base: https://github.com/halfdane
    - name: kbrd-space
      url_base: https://github.com/kbrd-space
  projects:
    - name: zmk
      remote: moergo
      revision: main
      import: app/west.yml
    - name: zmk-input-gestures
      remote: halfdane
      revision: main
    - name: zmk-anti-idle
      remote: kbrd-space
      revision: main
  self:
    path: config
