name: Build Go60

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        board: [go60_lh, go60_rh]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: Build
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DKEYMAP_FILE="${{ github.workspace }}/config/go60.keymap" -DEXTRA_CONF_FILE="${{ github.workspace }}/config/go60.conf"
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}
          path: build/zephyr/zmk.uf2
